### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'no_stream'

### ISSUE THREAD

**Issue by GiraffeRage** [SicariusSicariiStuff/Diffusion_TTS#11]
After installing all packages, this same error comes up regardless of if you used the one-click installer for oobaboonga, the terminal install, or if you try to select Diffusion_TTS in the webui and relaunch. 
Likewise, it occurs if you install this extension through the terminal or the webui. 

> text-generation-webui/extensions/Diffusion_TTS/script.py", line 78, in <module>
>     streaming_state = shared.args.no_stream  # remember if chat streaming was enabled
>                       ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Namespace' object has no attribute 'no_stream'

Line 78 of the python script is: 
> streaming_state = shared.args.no_stream  # remember if chat streaming was enabled

I looked around but did not see a reference to this error already.

This was running on Linux, specifically Ubuntu 22.04.3 LTS

Edit: it seems that parameter was removed as it was depreciated
https://github.com/oobabooga/text-generation-webui/commit/2aad91f3c9bc48eaee38ba313d2b928e6faa56e0

**Comment by emangamer** [comment]
same issue on windows, confirmed working on older oobabooga 

I asked BingAI to use it's copilot suggestion to fix the basic flag error, but it won't bring back the depreciated functions

It looks like you're encountering an `AttributeError` in your Python code. This error is occurring because the `Namespace` object `shared.args` does not have an attribute named `no_stream`. 

Here's what you can do to resolve this issue:

1. Ensure that the `no_stream` attribute is defined within the `args` Namespace. If it's supposed to be a command-line argument, check your argument parser setup to make sure `no_stream` is included.
2. If `no_stream` is a variable that should be set elsewhere in your code, verify that it is being set correctly before this line of code is executed.

Here's a simplified example of how you might define `no_stream` in an argument parser:

```python
import argparse

# Create the parser
parser = argparse.ArgumentParser(description='Process some integers.')

# Add the 'no_stream' argument
parser.add_argument('--no_stream', action='store_true', help='Disable stream')

# Parse the arguments
args = parser.parse_args()

# Now you can use args.no_stream
```

Make sure that the `no_stream` argument is being parsed before you try to access it in your `script.py`. If you're still having trouble, you might want to add some debugging prints before the error occurs to see what attributes are available in `shared.args`.

**Comment by waefrebeorn** [comment]
So it seems that this is because we do not call the new openai api function
https://github.com/oobabooga/text-generation-webui/issues/4591
they scrapped this old chat streaming back in nov 2023, so we have a need to fix how the chat streaming is called and listened to, looking into it now.

I'm lazy and might be forking and using a combination of Claude sonnet, Bingchat, and llama3 to refactor the code and make it run, also I may also update windows install instructions and then pull commits

here is the supposed solution for this issue, if you wanna do it, I'm busy
Claude 3 Sonnet helped make this
To fix the `script.py` file and use the new OpenAI compatible API instead of the deprecated one, we need to replace any references to the old API with the new API calls.

Here's how you can modify the `script.py` file:

1. Remove the following line from the imports:

```python
from modules import chat, shared, tts_preprocessor, ui_chat
```

2. Replace the line `shared.processing_message = "*Is recording a voice message...*"` in the `input_modifier` function with:

```python
print("*Is recording a voice message...*")
```

3. In the `output_modifier` function, replace the following lines:

```python
shared.processing_message = "*Is typing...*"
```

with:

```python
print("*Is typing...*")
```

4. Remove the following lines from the `output_modifier` function:

```python
if params['model_swap']:
    unload_llm()
    load_llm()
```

5. Add the following imports at the top of the file:

```python
import requests
import json
```

6. Replace the call to `unload_llm()` and `load_llm()` with a function that calls the OpenAI compatible API. For example:

```python
def call_openai_api(prompt):
    url = "http://127.0.0.1:5000/v1/completions"
    headers = {
        "Content-Type": "application/json"
    }
    data = {
        "prompt": prompt,
        "max_tokens": 200,
        "temperature": 1,
        "top_p": 0.9,
        "seed": 10
    }
    response = requests.post(url, headers=headers, json=data)
    return response.json()["choices"][0]["text"]
```

7. In the `output_modifier` function, replace the lines where `unload_llm()` and `load_llm()` were called with `call_openai_api(string)`.

After making these changes, the `script.py` file should work with the new OpenAI compatible API instead of the deprecated one.

Note that you might need to adjust the API endpoint URL, headers, and data payload based on your specific requirements and the API documentation provided in your question. Additionally, you might need to handle error cases and implement error handling in the `call_openai_api` function.

**Comment by SicariusSicariiStuff** [comment]
Thank you for the awesome suggestions, you are welcomed to fork the project or send a pull request.
If you can get this to work for windows users it would be really great.
This project is well deserved of some love, feel absolutely free to take over !

**Comment by waefrebeorn** [comment]
> Thank you for the awesome suggestions, you are welcomed to fork the project or send a pull request. If you can get this to work for windows users it would be really great. This project is well deserved of some love, feel absolutely free to take over !

I made a pull request and changed the ReadMe.md to update the changes

**Comment by SicariusSicariiStuff** [comment]
fixed
